name: saobracajke
description: "A Flutter application for traffic accident reporting using Serbian Open Data."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.2.0
  path: ^1.9.1
  path_provider: ^2.1.5
  sqflite: ^2.4.2
  archive: ^4.0.7
  intl: ^0.20.2
  fl_chart: ^1.1.1
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  flutter_map_marker_cluster: ^8.2.2
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  sqflite_common_ffi: ^2.4.0+2

flutter:
  uses-material-design: true
  assets:
    - assets/db/serbian_traffic.db.zip
